config/routes.rb
Rails.application.routes.draw do
  resources :shorten_urls, only: [:new, :create, :edit, :update, :show, :destroy]
  # custom 404
  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ]
  match "/401" => "errors#error401", via: [ :get, :post, :patch, :delete ]
  get '/:short_url', to: 'shorten_urls#send_to_url'
  get '/s/admin/:admin_url', to: 'shorten_urls#admin_send_to_url'
  root to: 'shorten_urls#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shorten_url.rb
class ShortenUrl < ApplicationRecord
  has_many :url_clicks
  default_scope { order(created_at: :desc) }
  validates :original_url, presence: { message: "Must be given" }
  validates :original_url, url: true

  before_create :generate_short_url
  before_create :generate_admin_url
  # before_create :find_duplicate

  enum status: { active: 0, inactive: 1 }
  validates :status, inclusion: { in: statuses.keys, message: "%{value} is not a valid status" }

  # Check a unique URL for a given web address before saving it into the DB
  def generate_short_url
    short_url = unique_url

    # check if this is a duplicate
    if ShortenUrl.where(short_url: short_url).exists?
      # try again
      generate_short_url
    else
      self.short_url = short_url
    end
  end

  def generate_admin_url
    admin_url = unique_url

    # check if this is a duplicate
    if ShortenUrl.where(admin_url: admin_url).exists?
      # try again
      generate_admin_url
    else
      self.admin_url = admin_url
    end
  end

  def is_duplicate?
    ShortenUrl.where(original_url: original_url).exists?
  end

  def new_url?
    find_duplicate.nil?
  end

  # def sanitize
  # self.original_url.strip!
  # self.sanitize_url
  # end

  def active?
    return true if status == 'active'

    false
  end

  def short
    "http://localhost:3000/#{short_url}"
  end

  def short_admin
    "http://localhost:3000/s/admin/#{admin_url}"
  end

  def unique_url
    [*'a'..'z', *'A'..'Z', *0..9].sample(6).join
  end
end

app/models/url_click.rb
class UrlClick < ApplicationRecord
  default_scope { order(created_at: :desc) }
  belongs_to :shorten_url, -> { order(created_at: :desc) }
  validates :shorten_url_id, presence: { message: 'Click must belong to a URL' }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Application Controller
class ApplicationController < ActionController::Base
  include ::ActionController::Cookies
  include Pagy::Backend
  protect_from_forgery with: :exception
  def not_found
    raise ActionController::RoutingError, 'Not Found'
  end
end

app/controllers/errors_controller.rb
# frozen_string_literal: true

# Errors Controller
class ErrorsController < ApplicationController
  def error404
    render status: :not_found
  end

  def error401
    render status: :unauthorized
  end
end

app/controllers/shorten_urls_controller.rb
# frozen_string_literal: true

# Shorten Urls Controller
class ShortenUrlsController < ApplicationController
  include ::ActionController::Cookies
  before_action :authenticate_request, only: %i[show edit update]
  before_action :authenticate, only: [:admin_send_to_url]

  # we may want this in the future
  # GET /urls
  # GET /urls.json
  # def index
  #  @page_title = 'Urls'
  #  @pagy, @urls = pagy(ShortenUrl.all, items: 100)
  #
  #  respond_to do |format|
  #   format.html # index.html.erb
  #   format.json { render json: @url }
  #  end
  # end

  # GET /urls/1
  # GET /urls/1.json
  def show
    @page_title = 'URL'
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @url }
    end
  end

  # GET /urls/new
  # GET /urls/new.json
  def new
    @page_title = 'New URL'
    @url = ShortenUrl.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @url }
    end
  end

  # GET /urls/1/edit
  def edit; end

  # POST /urls
  # POST /urls.json
  # POST /urls.js
  def create
    @url = ShortenUrl.new(shorten_url_params)
    if @url.save
      command = AuthenticateUser.call(@url.admin_url)
      help_authenticate(command)
      respond_to do |format|
        format.html { redirect_to @url, notice: 'Short URL was successfully created.' }
        format.json { render json: @url, status: :created, location: @url }
        format.js { flash[:notice] = 'Short URL was successfully created' }
      end
    else
      @page_title = 'New URL'
      respond_to do |format|
        format.html { render action: 'new' }
        format.json { render json: @url.errors, status: :unprocessable_entity }
        format.js { flash[:alert] = @url.errors.full_messages.to_sentence }
      end
    end
  end

  # PUT /urls/1
  # PUT /urls/1.json
  # PUT /urls/1.js
  def update
    respond_to do |format|
      if @url.update_attributes(shorten_url_params)
        format.html { redirect_to @url, notice: 'Short URL was successfully updated.' }
        format.json { head :no_content }
        format.js { flash[:notice] = 'Short URL was successfully updated' }
      else
        @page_title = 'Edit URL'
        format.html { render action: 'edit' }
        format.json { render json: @url.errors, status: :unprocessable_entity }
        format.js { flash[:alert] = @url.errors.full_messages.to_sentence }
      end
    end
  end

  # DELETE /urls/1
  # DELETE /urls/1.json
  # we may want this in the future
  def destroy
    if @url.destroy
      respond_to do |format|
        format.html { redirect_to root_path }
        format.json { head :no_content }
      end
    else
      @page_title = 'Edit URL'
      format.html { render action: 'edit' }
      format.json { render json: @url.errors, status: :unprocessable_entity }
      format.js { flash[:alert] = @url.errors.full_messages.to_sentence }
    end
  end

  def send_to_url
    if ShortenUrl.where(short_url: params[:short_url]).exists?
      @link = ShortenUrl.where(short_url: params[:short_url]).first
      if @link.active?
        # Create new click
        UrlClick.create!(shorten_url_id: @link.id)
        redirect_to @link.original_url
      else
        redirect_to '/404', flash: { alert: 'URL has expired' }
      end
    else
      redirect_to '/404', flash: { alert: 'URL not found' }
    end
  end

  def admin_send_to_url
    @url = ShortenUrl.where(admin_url: params[:admin_url]).first
    redirect_to @url
  end

  def authenticate
    command = AuthenticateUser.call(params[:admin_url])
    help_authenticate(command)
  end

  private

  def help_authenticate(command)
    if command.success?
      # render json: { auth_token: command.result }
      cookies.encrypted[:jwt] = { value: command.result, httponly: true, expires: Time.now + 1.day }
    else
      # render json: { error: command.errors }, status: :unauthorized
      redirect_to '/401', flash: { alert: command.errors[:authentication].to_sentence }
    end
  end
  def authenticate_request
    jwt = cookies.encrypted[:jwt]
    @url = AuthorizeApiRequest.call(jwt, params[:id]).result
    redirect_to '/401', flash: { alert: 'Not Authorized' } unless @url
    # format.json { render json: { error: 'Not Authorized' }, status: 401 unless @link }
  end

  # Never trust parameters from the scary internet
  # only allow the white list through.
  def shorten_url_params
    # extend with your own params
    accessible = %i[original_url status]
    params.require(:shorten_url).permit(accessible)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
include Pagy::Frontend

  def flash_class(level)
    case level
      when :notice then "alert alert-info"
      when :success then "alert alert-success"
      when :error then "alert alert-error"
      when :alert then "alert alert-error"
    end
  end

end

app/helpers/shorten_urls_helper.rb
module ShortenUrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LinkShortener</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title><%= @page_title ? @page_title: 'Welcome' %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- We defined this stuff -->
    <meta name="description" content="Link Shortener">
    <meta name="author" content="Sunjay Dhama">
    <link rel="icon" href="../../favicon.ico">

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->
  </head>

  <body>
    <%= render 'partials/header' %>
    <section>
      <div class="container py-5 bg-faded">
        <%= render 'partials/alerts' %>
        <%= yield %>
      </div>
    </section>
  </body>
</html>

app/views/partials/_alerts.html.erb
<div id="flash">
  <% if flash[:notice] %>
    <div class="alert-content">
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <i class="fa fa-check" aria-hidden="true"></i>
        <%= flash[:notice] %>
      </div>
    </div>
  <% end %>
  <% if flash[:alert] %>
    <div class="alert-content">
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <i class="fa fa-times" aria-hidden="true"></i>
        <%= flash[:alert] %>
      </div>
    </div>
  <% end %>
</div>

app/views/partials/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class=" <%= params[:controller] == 'link_shortener' ? 'nav-item active' : 'nav-item'%>"><%= link_to 'Home', root_path, class: "nav-link" %></li>
    </ul>
  </div>
</nav>

app/views/partials/_link.html.erb
<% if @url.errors.any? %>
  <p>
    <a href="https://www.quora.com/What-does-it-mean-when-I-am-asked-for-a-valid-URL">What is a valid URL?</a>
  </p>
<% else %>
  <% if @url.present? %>
    <h2>Url:
      <%= @url.original_url %>
    </h2>
    <h2>Clicks:
      <%= @url.url_clicks.count %></h2>
    <h2>Status:
      <%= @url.status.humanize %></h2>
    <h2>Short Url:
      <%= link_to @url.short, @url.short, target: '_blank', id: "short_url" %></h2>
    <h2>Admin:
      <%= link_to @url.short_admin, @url.short_admin, target: '_blank', id: "short_admin" %></h2>
    <%= link_to 'Edit', edit_shorten_url_path(@url), class: 'btn btn-primary', id: 'Edit' %>
  <% end %>
<% end %>

app/views/shorten_urls/_form.html.erb
<%= simple_form_for(@url, validate: true, url: (@url.new_record? ? shorten_urls_path(@url) : shorten_url_path(@url)), html: { class: 'form-inline', id: 'url_new'}, remote: true, authenticity_token: true) do |f| %>
  <%= f.error_notification %>
  <%= f.input :original_url, as: :text, label: false, placeholder: 'Paste a link to shorten it', input_html: { required: true }, error: 'Invalid URL' unless @url.persisted? %>
  <%= f.input :original_url, as: :text, label: false, disabled: true, placeholder: 'Paste a link to shorten it',  input_html: { required: true }, error: 'Invalid URL' unless @url.new_record? %>
  <%= f.input :status, label: false, as: :select, prompt: "Select status", collection: ShortenUrl.statuses.keys unless @url.new_record? %>
  <%= f.button :submit, "Shorten", html: { class: 'btn btn-primary mb-2'} %>
<% end %>

app/views/shorten_urls/create.js.erb
$("#flash").html('<%= j render "partials/alerts" %>').fadeOut(3000);
$("#link").html("<%= j render partial: 'partials/link', locals: {url: @url} %>");
$("#url_new").submit(function(e) {
  $(this).resetClientSideValidations();
  $("#flash").html('<%= j render "partials/alerts" %>').fadeIn(3000);
});
$(this).enableClientSideValidations();

app/views/shorten_urls/edit.html.erb
<%= render 'form', url: @url %>
<div id="link"></div>

app/views/shorten_urls/index.html.erb
<!-- 'access_level' must be set to 1 or 2 to view this page -->
<%= link_to 'New url', new_shorten_url_path %>
<% if @urls.any? %>
  <h3>Number of Urls:
    <%= @number_of_urls %></h3>
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th scope="col">URL</th>
        <th scope="col">Shortened URL</th>
        <th scope="col">Status</th>
        <th scope="col">Created At
        </th>
        <th scope="col">Edit
        </th>
        <th scope="col">Delete
        </th>
      </tr>
    </thead>

    <tbody>
      <% @urls.each do |url| %>
        <tr>
          <th scope="row"><%= link_to url.original_url, shorten_url_path(url) %></th>
          <td><%= url.short_url %></td>
          <td><%= url.status %></td>
          <td><%= url.created_at.to_time.strftime('%B %e %H:%M' ) %></td>
          <td><%= link_to 'Edit', edit_shorten_url_path(url) %></td>
          <td><%= link_to 'Destroy', url, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= pagy_nav_bootstrap(@pagy).html_safe %>

<% else %>
  <p>There are no urls!</p>
<% end %>

<br>

app/views/shorten_urls/new.html.erb
<%= render 'form', url: @url %>
<div id="link"></div>

app/views/shorten_urls/show.html.erb
<%= render partial: 'partials/link', locals: {url: @url} %>

app/views/shorten_urls/update.js.erb
$("#flash").html('<%= j render "partials/alerts" %>').fadeOut(3000);
$("#link").html("<%= j render partial: 'partials/link', locals: {url: @url} %>");
$("#url_new").submit(function(e) {
  $(this).resetClientSideValidations();
  $("#flash").html('<%= j render "partials/alerts" %>').fadeIn(3000);
});
$(this).enableClientSideValidations();